### PR TITLE
Add DAGsHub to resources

### PR DESCRIPTION
**Pull request by deanp70**

### CODE REVIEW

**Review by DaisyJDiaz — APPROVED** [review]

**Comment by deanp70** [comment]
@DaisyJDiaz I resolved the conflict in the merge

**Comment by deanp70** [comment]
Gentle reminder, It would be great to have this approved.

Thanks in advance!

**Comment by rstojnic** [comment]
@deanp70 sorry for the slow reply here! It's not clear to me if your tool fits in any of our sections because it seems to be a whole project management tool. What other similar tools exist out there, perhaps we should seed a new section? Or maybe the first section of "hosting pretrained models" is the most relevant although you guys do much more?

**Comment by deanp70** [comment]
> @deanp70 sorry for the slow reply here! It's not clear to me if your tool fits in any of our sections because it seems to be a whole project management tool. What other similar tools exist out there, perhaps we should seed a new section? Or maybe the first section of "hosting pretrained models" is the most relevant although you guys do much more?

No worries. DAGsHub definitely hosts pretrained models, but can also manage the data & model files, code and experiments, in a reproducible way. So if you want you can put is in either of these categories. With respect to other tools, you can think of DAGsHub as combining git + dvc + mlflow, with dedicated data science features (notebook diffing, data comparison). Not sure if this is helpful in defining a new category, but lmk what you think? If I had to define a category it would be "Managing and hosting of research code, data & models"

**Comment by rstojnic** [comment]
Added to the first section for model hosting as I think that's most relevant - 943f5e525eceeed02af482317db907f5834d72ab. Hope that my description is accurate (format is following other entries in the category)

**Pull request closed without merging**
